### ISSUE TITLE
Basic Setup Help

### ISSUE THREAD

**Issue by psbrandt** [omoponfhir/omopv5fhir-pgsql#2]
Hi,

I've been trying to get the latest master set up on my test database, but haven't had much luck unfortunately. So, I decided to try and get things running using your test database instead. I've created the following Compose file that sets up OMOP on FHIR using the Docker files you provide:

```yaml
# docker-compose.yml
version: "3"
services:
  omoponfhir-main:
    build:
      context: https://github.com/omoponfhir/omoponfhir-main.git#3be4f61674b5b62bffcf7b3a10c725ad20190f41
    restart: unless-stopped
    ports:
      - "9090:8080"
    environment:
      - JDBC_URL=jdbc:postgresql://omopv5fhir-pgsql:5432/postgres
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=i3lworks
    networks:
      omoponfhir:
  omopv5fhir-pgsql:
    build:
      context: https://github.com/omoponfhir/omopv5fhir-pgsql.git#0f21fcf5fb359b14f725d968b937d77a5a048117
    restart: unless-stopped
    ports:
      - "6543:5432"
    networks:
      omoponfhir:
networks:
  omoponfhir:
``` 

To recreate my setup, copy the above into a `docker-compose.yml` file, then run:

```sh
docker-compose up omopv5fhir-pgsql
```
Once the data is loaded, hit <kbd>Ctrl+C</kbd> and run:

```sh
docker-compose up
```
In my case, at this point it seems like the WAR file is deployed, and the application started up without errors. My question, for now, is how do I actually retrieve the resources? I did manage to dig up the Basic Authentication credentials [here](https://github.com/omoponfhir/omoponfhir-stu3-server/blob/c2ad29b42cd5d872535e34b80f56f9ac4719de1d/src/main/java/edu/gatech/chai/omoponfhir/security/Authorization.java#L73), but I can't seem to actually find any resources. Here are some examples of what I've tried:

### Search For Patient by Name

```sh
curl  -H 'Authorization: Basic Y2xpZW50X29tb3A6c2VjcmV0' 'http://localhost:9090/omoponfhir-stu3/fhir/Patient?name=Solo'
```
```json
{
  "resourceType": "Bundle",
  "id": "83a50675-0a10-452b-bfe5-ed812a149f63",
  "meta": {
    "lastUpdated": "2019-12-31T04:03:22.411+00:00"
  },
  "type": "searchset",
  "total": 0,
  "link": [
    {
      "relation": "self",
      "url": "http://localhost:9090/omoponfhir-stu3/fhir/Patient?name=Solo"
    }
  ]
}
```

### Find Patient by CDM ID

```sh
curl  -H 'Authorization: Basic Y2xpZW50X29tb3A6c2VjcmV0' 'http://localhost:9090/omoponfhir-stu3/fhir/Patient/1'
```
```json
{
  "resourceType": "OperationOutcome",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">ERROR</td><td>[]</td><td><pre>Resource Patient/1 is not known</pre></td>\n\t\t\t\t\t\n\t\t\t\t\n\t\t\t</tr>\n\t\t</table>\n\t</div>"
  },
  "issue": [
    {
      "severity": "error",
      "code": "processing",
      "diagnostics": "Resource Patient/1 is not known"
    }
  ]
}
```

### Search for Condition by Code

```sh
curl  -H 'Authorization: Basic Y2xpZW50X29tb3A6c2VjcmV0' 'http://localhost:9090/omoponfhir-stu3/fhir/Condition?code=428'
```
```json
{
  "resourceType": "Bundle",
  "id": "1a376385-e281-4aed-a075-c151b246bd42",
  "meta": {
    "lastUpdated": "2019-12-31T04:15:44.877+00:00"
  },
  "type": "searchset",
  "total": 0,
  "link": [
    {
      "relation": "self",
      "url": "http://localhost:9090/omoponfhir-stu3/fhir/Condition?code=428"
    }
  ]
}
```
Any help or a perhaps a pointer to the appropriate documentation would be greatly appreciated.
